---
name: Publish Docker Image

on:
  push:
   branches: main


env:
  REGISTRY: https://hub.docker.com/r/justinbather/godb
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to docker hub
        uses: docker/login-action@v3
        with: 
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

      - name: Extra meta for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with: 
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


