---
name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Build
      run: make godb

    - name: Start Server
      run: |
        go run cmd/server/server.go &
        sleep 5

    - name: Test
      uses: robherley/go-test-action@v0.1.0

