---
name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Build
      run: make godb

    - name: Test
      run: go run cmd/server/server.go
      uses: robherley/go-test-action@v0.1.0

